#ifndef _S5P4418_PERIPH_H
#define _S5P4418_PERIPH_H

enum periph_id {
    PERIPH_ID_UART0 = 51,
    PERIPH_ID_UART1,
    PERIPH_ID_UART2,
    PERIPH_ID_UART3,
    PERIPH_ID_UART4,
    PERIPH_ID_UART5,
    PERIPH_ID_I2C0 = 57,
    PERIPH_ID_I2C1,
    PERIPH_ID_I2C2,
    PERIPH_ID_SPI0 = 60,
    PERIPH_ID_SPI1,
    PERIPH_ID_SPI2,

    PERIPH_ID_NONE = -1,
};

#endif
